### ISSUE TITLE
When submitting a post before the 5 minute limit, the post disappears no draft is created.

### ISSUE THREAD

**Issue by Mustard5** [Zappl/Zappl#1]
I posted, then posted again within the five minute posting limit.  I received a warning about posting once every five minutes.  I clicked on the the popup warning and then most post disappears and no draft is created.

I would expect that it would remain on my screen afterwards and be available for submission again after five minutes has elapsed.

**Comment by Zappl** [comment]
Which browser are you using and on what system?

**Comment by Zappl** [comment]
Should be fixed next server reload.
