### ISSUE TITLE
Zappl Bug Detected: My First Contribution

### ISSUE THREAD

**Issue by yemmighto** [Zappl/Zappl#1]
Was scrolling through some chat on utopian discord chat room, when i saw some discussion about zappl.com been eligible as an open source project. it is always a good thing bring in open source project for steemian to be able to contribute to the site development.  Giving it a try i detect some bugs (non functioning button on zappl)

### Comment Not Showing 
It was so surprising not been privilege to able to view comment on zappl.com. it is really not good and need to be fix urgently, check screenshot below and check the arrow mark red
![sappy 2.PNG](https://steemitimages.com/DQmWwmBqPqNbcKBJiQJWfVR59k2BUrPoMPvfmFV545Ebh6v/sappy%202.PNG)

second screenshot

![sappy.PNG](https://steemitimages.com/DQmcsXm6ZReVZX7fPyAmJ3ms62LRXPPi7jmH4kT5aeSe8Ym/sappy.PNG)

we should be giving the access/privilege to be able to view comment of zappl post through zappl.com
kindly check the video below so you can understand what am saying more
https://youtu.be/RNSa9YNnR9w

### Showing 2 upvoting sign
one thing i do not actually understand is that i saw two upvoting sign on each zappl post where by one one is functioning as an upvoting button while the second one is not fuctioning at all
check screenshot below
![upvoing.PNG](https://steemitimages.com/DQmUWM9pAWfyPQ9vMvbfN8dNzXhJA179w9jVczKygoTpALC/upvoing.PNG)
you can see the 2 upvoting button in the red circle

![upvoing2.PNG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510759411/qcwpziv4ssuzrxztplnj.png)
another screenshot

check video below
https://youtu.be/iObMog0q9Xw

I hope this can be look into and correction will be made on time.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@valchiz/zappl-bug-detected-my-first-contribution">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Zappl** [comment]
were already aware of these.

The comments show you have comments because we haven't changed the method of it counting yet. We filter out steemit comments or comments made on any other app.

The buttons already being worked on.
