### ISSUE TITLE
Gif image corrupted icon on zappl post(video Included)

### ISSUE THREAD

**Issue by ezioronaldo** [Zappl/Zappl#11]
#### Expected behavior
I expected to see the preview of gif image normally on zappl

#### Actual behavior
What i found that whenever i am trying to upload a gif file on zappl, it is not showing the gif preview and not only that it does'nt even show the still image and it shows the image icon as corrupted image.
#### How to reproduce
1. Log in to zappl.com
2. create and new post
3. Upload a gif image file
4.You will see no image even after uploading complete It shows corrupted image icon

* Browser: Chrome
* Operating system: Win 7 ultimate 64bit

#### Recording Of The Bug
![Zapppl bug.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517130502/cgnc66vhmxeeyej5cfzv.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@techoverlords/gif-image-corrupted-icon-on-zappl-post-video-included">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Zappl** [comment]
We'll look into this for sure.

**Comment by Zappl** [comment]
We're currently unable to replicate this.
