### ISSUE TITLE
zappl key permissions-Null

### ISSUE THREAD

**Issue by Marshalllife** [Zappl/Zappl#13]
#### Expected behavior
on zappl website the permission keys can not be shown like how  the steemit permission page  shows it, the keys are supposed to be shown when users click *show posting key*. 
users sees the regular keys and   **no show active  keys or login to show** 

#### Actual behavior

![IMG_20180206_171325_462.JPG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517933622/nvqttsjaa1lasohieq3j.jpg)
 the key show posting keys above doesn't work or does not trigger the posting keys to show on zappl website. 
all key looks null or not linked to the account or maybe not responding. 

#### How to reproduce
login to zappl website, click on zappl settings, click the permission (also when that is clicked it seems  its not working) but click the permission and you will see the keys that are not responding especially  **show posting key that is not responding**

* Browser: 
![IMG_20180206_173640_204.JPG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517935054/e5zrko4hnkobphctarmq.jpg)

* Operating system:
![IMG_20180206_173628_927.JPG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517935069/wpbme3c2pjrd3x5xurac.jpg)

#### some spotted bugs

* 1
![IMG_20180206_173510_328.JPG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517935118/j0oq7tx8srri5zwtsdgm.jpg)
*2017 is still show on the company resev.. typo* also text is too light make it bold a little. 

* 2
![IMG_20180206_173541_914.JPG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517935242/sja8ippbsmyyyagokxrh.jpg)

looks like its not working or not responding when clicked, just Dormant and dead, 
- zappl dev should kindly look into it, make it highlight when clicked, so a user can tell when its clicked or not clicked. 

text is light make it bolder. 
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@marshalllife/zappl-key-permissions-null">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Zappl** [comment]
This is on purpose.

**Comment by Marshalllife** [comment]
Okay if you say so 👌
