### ISSUE TITLE
Cannot publish posts with Chinese characters in zappl

### ISSUE THREAD

**Issue by yuxir** [Zappl/Zappl#15]
I have been trying to post in Zappl and have discovered a strange behavior.  My posts with plain English can be published without any problem. However, if I entered any Chinese characters in the post content, the post won't be published. 

For example, if I enter the following Chinese characters:
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518394555/cohjrfq0xjqrzwqhkcqb.png)

After clicking "Post", a loading image will be showing for a couple of minutes:

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518394717/akbdsitypde8p7oyxxuk.png)

However, the posts won't be published.

#### Expected behavior
The post should be published - no mater if Chinese characters are included or not as the underlying Steem blockchain accepts multiple language posts.

#### Actual behavior

The loading image is showing for a couple of minutes then disappeared. The posts won't be published without any error message given.

#### How to reproduce

Open https://zappl.com and use your steemit username/posting key to login.
Enter Chinese characters as title and body.
Click 'Post' button.

* Browser:  Chrome 64.0.3282.140
* Operating system: Windows 10 64 bit

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@yuxi/cannot-publish-posts-with-chinese-characters-in-zappl">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Zappl** [comment]
We will look into this.

**Comment by Zappl** [comment]
Should now be able to use them in the body, since title creation is being gotten rid of that should no longer be a factor.
