### ISSUE TITLE
zappl App | Unable to save/load drafts

### ISSUE THREAD

**Issue by dheerajsharma14** [Zappl/Zappl#16]
I was trying out the new [Zappl](https://Zappl.com) app and as I was in a hurry wanted to use the Save Draft functionality. I wrote some piece and saved it as draft but when I clicked on Show Drafts, it was no where to find and got lost.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518612135/n0potakezf3sizmja9dv.png)

#### Expected behavior
When user clicks on "Save as Draft" button in "Create Zap" popup, the contents of the Zap should be saved as draft which can be opened or accessed from "Show Save Drafts" link/button in the "Create Zap" popup. Also, a message that Draft has been saved successfully is no shown to the user.

#### Actual behavior
When user clicks on "Save as Draft" button in "Create Zap" popup, the popup is closed giving user an impression that draft has been saved. When you try to access the saved draft, using "Show Save Drafts" link/button in the "Create Zap" popup then nothing is shown to the user. 

#### How to reproduce
1. Login to [zappl.com](http://zappl.com) applicatio using Google Chrome browser.
2. Click on Create Zap button to open the popup to create zap.
3. Write some text in title and body.
4. Click on Save as Draft button to save and close the popup
5. Now again click Create Zap button to open the popup to create zap.
6. Click on "Show Save Drafts" link/button and see the issue that your draft is no longer available anywhere.

* Browser: Google Chrome (Version 64.0.3282.140 (Official Build) (64-bit))
* Operating system: macOS High Sierra v10.13

#### Recording Of The Bug
To reproduce the issue, I have created a screen recording as well which can be found at the link: [Screen Recording Link](https://drive.google.com/file/d/1UxxyQfK6RdSaxfQgQPRZnCf1mc2cbRwW/view)    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@devilonwheels/zappl-app-or-unable-to-save-load-drafts">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Zappl** [comment]
We will look into this issue.

**Comment by Zappl** [comment]
should be corrected
