### ISSUE TITLE
zappl App | Loader icon keeps spinning until you refresh the page

### ISSUE THREAD

**Issue by dheerajsharma14** [Zappl/Zappl#18]
Another round on exploring the [Zappl.com](https://zappl.com) app, I noticed another issue where when you click "Follow" button next to your own profile, the loading spinner keep on loading and does not go away until you refresh the whole browser page again. Rest of the operations keep of working fine.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518755225/e71xhntzgkcoyt47yzfm.png)

#### Expected behavior
Loader icon should always go away after completion of any operation in the application. 

#### Actual behavior
Loader icon keep on spinning once you click "Follow" button next to your own profile. You will have to refresh the page to get rid of it. By the way, in first place, follow button should not be visible for my own profile as I should not be allowed to follow myself. 

#### How to reproduce
1. Login to [zappl.com](zappl.com) application using Google Chrome browser on a Macbook. You will be landed on the Home page of the application.
2. Click on your small profile photo on the upper right corner in header bar to navigate to your profile page.
3. Once you load your own profile page, you will notice a "+ Follow" button coming on the right hand side of profile header. Click on it and a loader icon will start spinning.
4. Keep waiting for sometime, the loader icon will keep spinning. Navigate away from the page to other sections of the application and notice that loader icon still keep spinning. Load some feed and keep scrolling, the feed loads but loader icon keep spinning.
5. Refresh the browser tab/page to get rid of loader icon.

##### Environment Details
* Browser: Google Chrome (Version 64.0.3282.140 (Official Build) (64-bit))
* Operating system: macOS High Sierra v10.13

#### Recording Of The Bug
To reproduce the issue, I have created a screen recording as well which can be found at the link: [Screen Recording Link](https://drive.google.com/file/d/1yKLuEcpjuq1aQ2Vuxsctj19b1Q3_32pp/view)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@devilonwheels/zappl-app-or-loader-icon-keeps-spinning-until-you-refresh-the-page">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Zappl** [comment]
This is a loading issue when its taking time to connect to a node. This isn't a bug, it depends where you are in relation to one of the servers.

**Comment by codingdefined** [comment]
@Zappl Why the user is getting Follow button on its own profile?
