### ISSUE TITLE
Can not copy and paste image - Zappl

### ISSUE THREAD

**Issue by penguine99** [Zappl/Zappl#19]
#### Expected behavior
Image should be pasted after copying it from random site.

#### Actual behavior
Unable to paste image after copying from random site.

#### How to reproduce
1. Signup / Login to [Zappl](www.zappl.com).
2. Click on 'Create Zap' from Home screen.
3. Copy an image from different source.
4. Paste it to Description section.

* Browser: Chrome
* Operating system: Windows 10

#### Recording Of The Bug

![bug1.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518944645/ymbcavhjsoffngf097tq.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tanvirrahman/can-not-copy-and-paste-image-zappl">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Zappl** [comment]
Zappl doesn't yet support auto embed methods. Were currently working on auto embed methods for url website cards images and videos.
