### ISSUE TITLE
Does not show cover photo - Zappl

### ISSUE THREAD

**Issue by penguine99** [Zappl/Zappl#20]
#### Expected behavior
Cover photo should be visible if it is set.

#### Actual behavior
Cover photo is not showing though it was previously set.

#### How to reproduce
1. Signup / Login to [Zappl](www.zappl.com).
2. Go to Profile section.
3. Observe Cover photo.
* Browser: Google Chrome
* Operating system: Windows 10

#### Recording Of The Bug
![bug.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518984812/xwzuub94h0ht58mvi9dv.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tanvirrahman/does-not-show-cover-photo-zappl">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mktcode** [comment]
well... this is not really a bug but a missing feature that people are used to from steemit and busy. but zappl itself does not even have an option to set a header image.

**Comment by Zappl** [comment]
Already in the works one of the next updates.
