### ISSUE TITLE
[Zappl] - XSS in search bar

### ISSUE THREAD

**Issue by jayserdny** [Zappl/Zappl#23]
#### Expected behavior
XSS filter evasion should cover each edge case. All possible XSS code should be rejected.

#### Actual behavior
XSS filter evasion is not working for input text method, DIV expression method, and WAF ByPass Strings for XSS.

#### How to reproduce
Here are all the urls you can test to reflect the XSS bug:

https://gist.github.com/jayserdny/bf23a88197aabe2cbc5bae96fc31a198

#### Environment
* Browser: Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)
* Operating system: macOS High Sierra

#### Some screenshots of the bug
![Screen Shot 2018-03-13 at 2.21.11 AM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520922083/gvkdz3uapqwlyzn9hzrg.png)
![Screen Shot 2018-03-13 at 2.21.42 AM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520922117/d0m1tytzwftijzjdqosy.png)
![Screen Shot 2018-03-13 at 2.22.06 AM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520922138/gs90mk5dw2orogzujwuo.png)
![Screen Shot 2018-03-13 at 2.23.22 AM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520922223/nuetwib2c6vnnjacqndg.png)
![Screen Shot 2018-03-13 at 2.23.51 AM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520922243/umyzrjbic4vajxq9f9fi.png)
![Screen Shot 2018-03-13 at 2.24.26 AM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520922289/pa0s2cxkadksey8yjaih.png)    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@jaysermendez/zappl-xss-in-search-bar">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Zappl** [comment]
should be resolved

**Comment by attritionorg** [comment]
@zappl Can you link to the fixing commit please?
