### ISSUE TITLE
No Title Writing Place Available in Zappl

### ISSUE THREAD

**Issue by amriadits** [Zappl/Zappl#24]
![2.PNG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521371683/m42ur8zklixfgh7xsqvw.png)
*There is no place to write the title*

#### Expected behavior
I have not made a post in Zappl for a long time. This time I tried to make a post again at https://zappl.com/ But there is an oddity there. Where zappl usually provide place of pstingan in the form of: Title, Content 240 characters remaining, image and video.

This is not available in the title field at zappl. After the post trial then the title is out "Zappl Post 20180318t103532131z". I hope post in Zappl as it used to provide the title place.

![U5drd4vdgzJyviStizdvbUBtXAhvTb7_1680x8400.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521371760/ufp4cpajqhazakpbxsty.png)
*I used to do capture and there is a place to write the title.*

![6.PNG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521371837/ol6vvk8mqyi4qbb9a4op.png)
*A disheveled title display in Steemit*

#### Actual behavior
When I do a post that there is no place the title will certainly be read in steemit as a dumb thing, because the title is messy and not appropriate. I have done a complete capture.
#### How to reproduce

You just need to open https://zappl.com/ then click what's happening? and you will see the bug. I use chrome and Windows 7 on my PC. The same bug also occurred when I was browsing on my android phone.

Browser: Chrome

Operating system: Windows 7

#### Recording Of The Bug
![anigif.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521371967/h4tqs98uxdrdlsft6wcn.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@amriadits/no-title-writing-place-available-in-zappl">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Zappl** [comment]
This is on purpose.
