### ISSUE TITLE
Impossible to change "CONFIGURATIONS" Settings - Zappl Desktop

### ISSUE THREAD

**Issue by Ana-Mari** [Zappl/Zappl#25]
I wanted to change my Voting configuration settings and although after pressing the "Save Changes" button the info box saying _"Voting(%) saved successfully"_ showed up **the change didn't take effect!** 

As well, I would like to know if the currently missing Post Title box (when creating a new Zap is some new setting (which btw I don't like, as the Zappl post appears awfully as on Steemit site same on other mirroring platforms like Busy.org, ChainBB.com etc.) or is just another bug???

**Comment by Zappl** [comment]
Ah its a ui issue it does change.

Also the title is being worked on, title form is being gotten rid of. It will look much better soon!
