### ISSUE TITLE
Comment count says 3, only 2 comments visible.

### ISSUE THREAD

**Issue by Mustard5** [Zappl/Zappl#3]
In this post, it states there are 3 comments but only 2 are displayed.  It appears that one of the comments was a 'comment on a comment' however, it is not displayed.

https://zappl.com/#!/zappl/jonny-clearwater/for-zappl-testing-purpose

![incorrectcommentcount](https://user-images.githubusercontent.com/378530/31943451-d2ce5800-b896-11e7-9694-ca0a4dea37f1.png)

-edit-

The third comment was probably made on through steemit.com
https://steemit.com/zappl/@jonny-clearwater/for-zappl-testing-purpose

**Comment by Zappl** [comment]
Yes if a post is made on steemit.com it won't show up so we will need to likely count out steemit comments in a number of comments its showing
