### ISSUE TITLE
hyperlinks not properly showing.

### ISSUE THREAD

**Issue by grey580** [Zappl/Zappl#3]
When adding hyperlinks the link is not clickable.

![image](https://user-images.githubusercontent.com/12612300/32968381-0687c5e8-cbaf-11e7-93d8-96840f4075a8.png)

Second page link is missing completely.

![image](https://user-images.githubusercontent.com/12612300/32968447-3bf2570c-cbaf-11e7-90bf-788bfb12ad23.png)

**Comment by Zappl** [comment]
We are aware of this issue its being worked on.

**Comment by Zappl** [comment]
Problem solved
