### ISSUE TITLE
Resteemed article via Zapple issue

### ISSUE THREAD

**Issue by BaltizarMonakken** [Zappl/Zappl#7]
Via the steemit website you can see that the second post is a resteemed article. On the zapple website that same post is not seen as a resteemed post. 

[screenshot 2017-11-30 22 03 57](https://user-images.githubusercontent.com/34140932/33463131-7d53f5c8-d61a-11e7-81d6-3e7969c438aa.png)

![screenshot 2017-11-30 22 06 43](https://user-images.githubusercontent.com/34140932/33463200-d4ea028c-d61a-11e7-9b08-2d3ccf3ffde9.png)

**Comment by Zappl** [comment]
Zappl don't pickup content made on other sites regardless. if its a resteem of something not made on zappl it won't show up.
