### ISSUE TITLE
Utopian Bug Hunting : Zappl interface

### ISSUE THREAD

**Issue by TheGoldenPhoenix** [Zappl/Zappl#9]
## What is Zappl?
**[Zappl](https://zappl.com/)** is a decentralized micro-blogging application that sits on top of the Steem Blockchain .
## The Reported bug is related to the graphic interface of Zappl .
When changing the screen size of the the browser window we can see that the strings and the follow boxes overflows the outlines and the borders.
#### Screenshot 1 (**screen size 100%**)
![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512841542/o0zltay0yg6mqjvwwxxr.png)
#### Screenshot 2 (**screen size 133%**)
![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512841758/wldgrkdxlcltlyg7l0v9.png)
#### Screenshot 3 (**screen size 150%**)
![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512841867/a4uoq1gtn2m2txfkidcr.png)

## The Testing Environment Details
Zappl Desktop : https://zappl.com/
OS: Windows 10
Browser: Firefox Quantum Version 57.0.2, December 7, 2017 (64-bit)
![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512842055/x92a9aahk3fqeemojvch.png)
 Tested also using chrome Version 57.0.0.12335.
## Steps to reproduce the bug :
1- Open **[Zappl](https://zappl.com/)** on your browser.
2- Login using your private posting key.
3- Now try to resize your browser using your **mouse** or the **keyboard** shortcuts (Ctrl+ the plus button) or just use your **browser**
![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512848123/ortagg4oaq38133tran7.png)
Thank you for reading & good luck (°¥°)

<hr>
<centre><h1><blockquote>𝕨𝕖 𝕘𝕠 𝕤𝕝𝕠𝕨 𝕓𝕦𝕥 𝕨𝕖 𝕘𝕠 𝕗𝕦𝕣𝕥𝕙𝕖𝕣 @thegoldenphoenix</blockquote></centre>
<hr>

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thegoldenphoenix/utopian-bug-hunting-zappl-interface">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Zappl** [comment]
Should now be fixed.
